### ISSUE TITLE
[Suggestion] Why is Quantum bundling icons?

### ISSUE THREAD

**Issue by rafaelgaldencio** [catho/quantum#169]
I was wondering about why we don't officially support @material-ui/icons instead of bundling them with the package.

I'm all forward to the idea of supporting an icon lib while not taking away the user's choice.

In this case, Quantum is forcing the user to use a set of icons in a specific way (a font file).

**Comment by rapahaeru** [comment]
Thanks for the suggestion @rafaelgaldencio.
We don't want to lose the facility of Quantum implementation. But this suggestion makes sense too.
So, we decided to reduce the number of icons. With that, we reduced to only 45 icons. 
That way, we still guarantee the quantum easy implementation and makes it optimised, like your suggest.
So i think we can close this issue. Ok?
Again, thanks.

**Comment by rafaelgaldencio** [comment]
Sure, that makes sense. Thank you. :)
