### ISSUE TITLE
[object Object] in the theme props

### ISSUE THREAD

**Issue by tcelestino** [catho/quantum#170]
Should it be like this?

![Screen Shot 2019-11-24 at 20 15 12](https://user-images.githubusercontent.com/190265/69503310-4248ce00-0ef7-11ea-9089-79c17745544d.png)

It has happened in the `<Dropdown />`.

**Comment by rapahaeru** [comment]
Thanks @tcelestino. This issue is in our backlog now.

**Comment by rapahaeru** [comment]
@tcelestino we decided that to resolve this problem, we should implement the styled component [ThemeProvider](https://styled-components.com/docs/advanced).

we added a history on backlog to implement this full theming support and all components will be updated.
This theming suport is called QuantumThemeProvider.

So, we doesnt need to fix this issue now, cause this implementation will solve it.

We gonna close this issue, for now. 

Thanks,
