### ISSUE TITLE
[Proposal] Adding description on <Dropdown />

### ISSUE THREAD

**Issue by tcelestino** [catho/quantum#204]
Maybe UX designers need to show a description to label on `<Dropdown />`, as print screen below:

![Screen Shot 2020-03-11 at 07 50 17](https://user-images.githubusercontent.com/190265/76409338-26721680-6386-11ea-9ab8-b535308ccdfa.png)

My proposal is add a new key in object to set on `items` props and render like print screen below:

![Screen Shot 2020-03-11 at 07 51 44](https://user-images.githubusercontent.com/190265/76409471-51f50100-6386-11ea-8083-0326c1319752.png)

**Comment by rapahaeru** [comment]
In a talk, we decided to drop this feat.
