### ISSUE TITLE
Radio Group problems when value prop is used

### ISSUE THREAD

**Issue by iagocaldeira** [catho/quantum#213]
https://www.loom.com/share/816d5e47452f441e99b7440e35215dd0

Regarding problems with controlling Radio Group component, when using 'value' prop the component behaviors as seen on the video.

**Comment by iagocaldeira** [comment]
I think this could be related to #197

**Comment by rapahaeru** [comment]
we think that issue was solved with this PR: https://github.com/catho/quantum/commit/38b0da5932c04c48b85132a1907feaf3cfe128af
Thanks!
