### ISSUE TITLE
Some types/interfaces are with props missed in its declaration

### ISSUE THREAD

**Issue by MichelAraujo** [catho/quantum#219]
For example the type `Model`, don’t recognize the prop `Header`, `HeaderText`, `Title` e etc, generate error below:
`Property 'Header' does not exist on type 'typeof Modal'.`

To work in the code is necessary ignore TS like this:
```
{/* // @ts-ignore */}
<Modal.Header>
{/* // @ts-ignore */}
<Modal.HeaderText>
```
This issue is tested in 4.1.1 version of the Quantum

**Comment by jmcoimbra** [comment]
@MichelAraujo @Thilara @jgpacker 
We must validate if this issue is really fixed to help close the issue.
