### ISSUE TITLE
helperText props on <Dropdown /> with class ErrorMessage

### ISSUE THREAD

**Issue by tcelestino** [catho/quantum#290]
### Describe the feature or problem you’d like to solve

When we're using `<Dropdown />` add props `helperText`, when this props is rendered the `span` wrapper has `ErrorMessage` class. It can see in the printscreen.

### Proposed solution

Changes class on props `helperText`

How will it benefit?

If a user did a test case to validations, if user to use `<Dropdown />` with props `helperText` the test case will fails. And, I believe that `helperText` isn't a error.

### Additional context

![Screen Shot 2021-01-23 at 16 48 54](https://user-images.githubusercontent.com/190265/105612427-eac41d80-5d9a-11eb-929e-6a506b520a68.png)

**Comment by MarcosViniciusPC** [comment]
helperText é exibido em um componente chamado HelperText que tem como base a estilização do InputErrorMessage e do ErrorMessage. Ao gerar a classe css do HelperText o styled component manteve o nome dos componentes base da estilização como nome da classe e isso pode ter causado confusão.
