### ISSUE TITLE
Error to compile .css

### ISSUE THREAD

**Issue by tcelestino** [catho/quantum#40]
When we are use to `import { Component... } from '@catho/quantum'` it is happening this error:

```
Failed to compile

./node_modules/rc-slider/assets/index.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> .rc-slider {
|   position: relative;
|   height: 14px;

This error occurred during the build time and cannot be dismissed.
```
It has happening in React App as much as in the React App + Next.

Talking about it with @allyssonsantos, we believe that is problem happens because the rc-slider is using .css files.

**Comment by alan-oliv** [comment]
Thank for pointing that @tcelestino. We are lookin' into that
