### ISSUE TITLE
Skeleton.Text

### ISSUE THREAD

**Issue by LucasFlaquer** [catho/quantum#437]
### Skeleton.Text html structure

when using the Skeleton.Text component it keeps logging this warning about HTML semantic issue:
![image](https://user-images.githubusercontent.com/22601978/186443813-8d8296ee-e82c-4a4d-97e7-47628829509b.png)

### Proposed solution
Refactor the Skeleton.Text component to use span as a generic inline element will not trigger this problem and because the base Skeleton uses a div with `display: inline-block` it will not have any problems due to this change

### Our Context
We use the Skeleton.Text inside the paragraph that contains a label and then the skelenton for the data that is displayed after an API call:
![image](https://user-images.githubusercontent.com/22601978/186445188-89d2f122-4d8c-4389-9a13-f98b22dd6564.png)
With the solution proposed it would make the HTML semantic and possible to use it inside a `<p></p>` or a `<div></div>`

**Comment by 2bfe26** [comment]
@LucasFlaquer  @jonatasprates 

already fixed at #488
