### ISSUE TITLE
TabbedView fluid

### ISSUE THREAD

**Issue by LucasFlaquer** [catho/quantum#517]
### Describe the feature or problem you’d like to solve

When using the component `<TabbedView />` with the *fluid* prop, if the amount of tabs is less than 3 the default size is settled to 33%, is possible to see this behavior in the image bellow:
![Captura de tela de 2023-07-26 10-25-30](https://github.com/catho/quantum/assets/22601978/978a939d-04c0-4ca6-bf1c-624a23bddd41)

this static width works fine when the component has 3 or more tabs but it dosen't with less than 3.

 . a idéia aqui é que ele esteja com a prop fluid habilitada para ocupar 100% do espaço. Notei que caso haja menos de 3 itens ele não faz esse comportamento como pode ver na imagem abaixo. Eu vi que a navegação está utilizando display: flex; pelo que testei aqui, utilizando flex-basis e flex-grow obteria um resultado semelhante para quantidades a partir de 3 e manteria com a largura 100% quando tiver menos

### Proposed solution
On way to solve it is removing the `widht: XX%` attribute and adding the following attributes to the NavItem element *when has the fluid prop enabled*: 
```css
flex-basis: 33.33%;
flex-grow: 1;
```
### How will it benefit?
with this update the component would look like the image bellow where the nav item buttons will fill the blank space:
![image](https://github.com/catho/quantum/assets/22601978/ef0c307b-5569-4cca-b10e-cf6568a8286f)

**Comment by rapahaeru** [comment]
hi @LucasFlaquer . Thanks for contribuiting with us.
In this case, we should have the approval by the designers from style guide.
We should align with them.
This changes was suggested by who?

**Comment by LucasFlaquer** [comment]
Hi @rapahaeru, first things first, when using the _fluid_ prop I'm expecting that the component buttons fill the whole space, so I think it might be an error in this styles.
this changes are necessary to fix the component and to procede with the proposed [layout](https://www.figma.com/file/s6wjtF5zLMeT6ZCkXSElgM/%5BOs-Imposs%C3%ADveis%5D-%C3%81rea-admin-%5BMinha-conta%5D?type=design&node-id=4852-15878&mode=design&t=UeJsotT3P8Ds1Qew-0) made by Mariana

**Comment by MarcosViniciusPC** [comment]
Apparently this is a bug. The width of each item is based on its content rather than the amount of children/Item passed to the component. I created a task to fix this

https://jirasoftware.catho.com.br/browse/QTM-531

**Comment by MarcosViniciusPC** [comment]
Released
