### ISSUE TITLE
<TabbedView /> 

### ISSUE THREAD

**Issue by LucasFlaquer** [catho/quantum#584]
### Describe the bug

The component `TabbedView />` as a prop called `activeTab`, the problem we faced is that if we need to change the active tab, the component doesn't provide any way to to do it

### Steps to reproduce the behavior

1. Set the component with a state that defines the active tab, change this tab by a click of a button
2. The component should be able to change the current tab
3. Error: The component does nothing

### Expected vs actual behavior

A expectation of the behavior is that the component could be able to change te current active tab when the activeTab prop value canges

**Comment by MarcosViniciusPC** [comment]
I checked the behavior of the component and it really doesn't update the selected tab when the value of the activeTab prop changes. The change makes sense, we will review the pr com to validate the implementation of the proposed solution to meet the expected behavior

**Comment by MarcosViniciusPC** [comment]
Resolved in https://github.com/catho/quantum/pull/585
