### ISSUE TITLE
The responsive grid not work in IE11

### ISSUE THREAD

**Issue by MichelAraujo** [catho/quantum#92]
The grid was implemented as follows:
```  
<Container>
      <Row>
        <Col xsmall={4} small={3} medium={4}>
          // Any div
        </Col>
        <Col xsmall={4} small={5} medium={8}>
          // Any div
        </Col>
      </Row>
 </Container>
```

In IE11 it does not work as expected, it does not recognize the columns.
Follow sample images.

How it should work:
![search_work](https://user-images.githubusercontent.com/1559393/59278343-306cba80-8c38-11e9-830f-5b464f52e000.png)

In IE11:
![search_not_work](https://user-images.githubusercontent.com/1559393/59278362-3bbfe600-8c38-11e9-8bfc-29611713151e.png)

**Comment by pedrohmorais** [comment]
@MichelAraujo we have a PR to fix it. Can you review please ?
https://github.com/catho/quantum/pull/106

**Comment by MichelAraujo** [comment]
Testing in IE 11 with browserstack is not working Grid system yet, but we are still evaluating if we really support this browser.

**Comment by rapahaeru** [comment]
This issue was closed with this PR -> https://github.com/catho/quantum/pull/106
