### ISSUE TITLE
Web-fonts with delay

### ISSUE THREAD

**Issue by Thilara** [catho/quantum#94]
When rendering the web-font on the page, it takes a few seconds to show the fonts.

![web-fonts](https://user-images.githubusercontent.com/44405493/59696873-3d9f2180-91c3-11e9-87b7-c526a5e201ea.gif)

**Comment by ggdaltoso** [comment]
Hi @Thilara 

This was fixed in #67 thanks to @tcelestino 

Could you, please, update to the latest version (1.16.0)?

**Comment by tcelestino** [comment]
@MichelAraujo, I've been talking with @allyssonsantos about it and he suggested to move `<GlobalStyle />` in _document.jsx_ from _app.jsx_. I did but it will improvement this behavior but don't resolve that. 

Ask the @alisson-suzigan about it because he was testing this in your project.

**Comment by rapahaeru** [comment]
we fixed it in #101.
Just clarify, now you need to add the `<GlobalStyle />` in `_document` instead of `_app`.
