### ISSUE TITLE
Button's height is not flexible

### ISSUE THREAD

**Issue by alisson-suzigan** [catho/quantum#98]
Using texts with breaklines the Button's height doesn't change, causing reading problems.

![iphone-5s](https://user-images.githubusercontent.com/5255042/60185948-3bf7de00-9801-11e9-82cf-7a0e3591cef3.png)

**Comment by ggdaltoso** [comment]
We implement the Button following UX guidelines which, one of then, can be found in [Material Design Guidelines](https://material.io/design/components/buttons.html#anatomy) recommending to not use to wrap text and to remain on a single line to improve legibility.

**Comment by alisson-suzigan** [comment]
I understand that it is not recommended, but even in Material Guideline example the button height is adjusted when it happens.

**Comment by pedrohmorais** [comment]
A solution has been proposed in this pull request. https://github.com/catho/quantum/pull/103
